### ISSUE TITLE
是否有基于杰里平台的蓝牙部分代码

### ISSUE THREAD

**Issue by yue184** [PING020903/AC695N-demo-xbox360-WindowsPC_only#3]
有无线蓝牙部分的代码吗

**Comment by PING020903** [comment]
有的，在这里 https://github.com/PING020903/AC695N-jieli--demo-GamePad/blob/main/sdk/apps/dongle/btstack_demo.c

**Comment by yue184** [comment]
收到，感谢博主，这个btstack我看了，目前杰里只实现了蓝牙的广播，蓝牙hci层和蓝牙controller层代码平台是实现了的，蓝牙host层代码没有，应该需要自己移植蓝牙协议栈

**Comment by PING020903** [comment]
> 收到，感谢博主，这个btstack我看了，目前杰里只实现了蓝牙的广播，蓝牙hci层和蓝牙controller层代码平台是实现了的，蓝牙host层代码没有，应该需要自己移植蓝牙协议栈

或许你应该找供应商问问有没有最新的 `soundbox` SDK，这个项目就是基于这个改的
